### PR TITLE
1.18.1 protocol (757)

### PR DESCRIPTION
**Pull request by iceiix**
https://minecraft.fandom.com/wiki/Java_Edition_1.18.1
https://minecraft.fandom.com/wiki/Java_Edition_1.18 (Caves & Cliffs: Part II)
 
https://wiki.vg/index.php?title=Protocol&oldid=16918 1.17.1
https://wiki.vg/Protocol https://wiki.vg/index.php?title=Protocol&oldid=17203 1.18.1
https://wiki.vg/index.php?title=Protocol&type=revision&diff=17203&oldid=16918 1.18.1 vs 1.17.1

### CODE REVIEW

**Comment by iceiix** [comment]
Not nearly complete. Major changes to chunk format again (every major release?), specifically  https://wiki.vg/index.php?title=Protocol&oldid=16918#Chunk_Data is now https://wiki.vg/Protocol#Chunk_Data_And_Update_Light. https://minecraft.fandom.com/wiki/Java_Edition_1.18#Chunk_format also summarizes the chunk format changes:

> * Chunk’s Level.Sections[].BlockStates & Level.Sections[].Palette have moved to a container structure in Level.Sections[].block_states.
> * Chunk’s Level.Biomes are now paletted and live in a similar container structure in Level.Sections[].biomes.
> * Chunk’s Level.CarvingMasks[] is now long[] instead of byte[].
> * Removed chunk’s Level and moved everything it contained up.
>   * Level.Entities has moved to entities.
Level.TileEntities has moved to block_entities.
Level.TileTicks and Level.ToBeTicked have moved to block_ticks.
Level.LiquidTicks and Level.LiquidsToBeTicked have moved to fluid_ticks.
Level.Sections has moved to sections.
Level.Structures has moved to structures.
Level.Structures.Starts has moved to structures.starts.
Level.Sections[].block_states has moved to sections[].block_states.
Level.Sections[].biomes has moved to sections[].biomes.
> * Added yPos the minimum section y position in the chunk.
> * Added below_zero_retrogen containing data to support below zero generation.
> * Added blending_data containing data to support blending new world generation with existing chunks.

many more fields in the new 0x22 packet. https://www.spigotmc.org/threads/chunk-data-in-1-18.536063/ has some discussion about biome changes. https://www.planetminecraft.com/blog/minecraft-1-18-technical-changes/ summarizes the technical changes ("for all the data pack creators, redstoners and other nerds in the Minecraft community", many won't affect us though).

**Comment by iceiix** [comment]
Screen Shot 2021-12-26 at 5 03 17 PM

**Comment by iceiix** [comment]
Next crash is thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', protocol/src/types/bit/map.rs:112:15, from stevenarella::world::World::load_chunk19_to_117 src/world/mod.rs:1074:30. The chunk section data structure changed:

https://wiki.vg/index.php?title=Chunk_Format&oldid=16986#Data_structure
https://wiki.vg/Chunk_Format#Data_structure
https://wiki.vg/index.php?title=Chunk_Format&type=revision&diff=17174&oldid=16986

Still begins with the block count short, parsed here:

```rust
                if self.protocol_version >= 451 {
                    let _block_count = data.read_u16::<byteorder::LittleEndian>()?;
                    // TODO: use block_count
                }
```

but then there are two paletted containers: for block states and biomes. Pre-1.18 only had block states. Getting a crash reading beyond the end of the bit map, of only two bits - is this right? This is new:

> When Bits Per Entry is 0, this array is empty (see [[#Single valued|Single valued palette

vs:

```rust
                let mut bit_size = data.read_u8()?;
                let mut mappings: HashMap<usize, block::Block, BuildHasherDefault<FNVHash>> =
                    HashMap::with_hasher(BuildHasherDefault::default());
                if bit_size == 0 {
                    bit_size = 13;
                } else {
                    let count = VarInt::read_from(&mut data)?.0;
                    for i in 0..count {
                        let id = VarInt::read_from(&mut data)?.0;
                        let bl = self
                            .id_map
                            .by_vanilla_id(id as usize, &self.modded_block_ids);
                        mappings.insert(i as usize, bl);
                    }
                }

                let bits = LenPrefixed::<VarInt, u64>::read_from(&mut data)?.data;
                let padded = self.protocol_version >= 736;
                let m = bit::Map::from_raw(bits, bit_size as usize, padded);
```

Is it even reading the correct data here? Examining the beginning of the packet:

```
% hexdump -C last-packet 
00000000  22 ff ff ff f7 ff ff ff  ff 0a 00 00 0c 00 0f 4d  |"..............M|
00000010  4f 54 49 4f 4e 5f 42 4c  4f 43 4b 49 4e 47 00 00  |OTION_BLOCKING..|
00000020  00 25 1f cf e7 f3 f9 fc  fe 7f 1f cf e7 f3 f9 fc  |.%..............|
00000030  fe 7f 1f cf e7 f3 f9 fc  fe 7f 1f cf e7 f3 f9 fc  |................|
*
00000140  fe 7f 00 00 00 03 f9 fc  fe 7f 0c 00 0d 57 4f 52  |.............WOR|
00000150  4c 44 5f 53 55 52 46 41  43 45 00 00 00 25 1f cf  |LD_SURFACE...%..|
00000160  e7 f3 f9 fc fe 7f 1f cf  e7 f3 f9 fc fe 7f 1f cf  |................|
*
00000270  e7 f3 f9 fc fe 7f 1f cf  e7 f3 f9 fc fe 7f 00 00  |................|
00000280  00 03 f9 fc fe 7f 00 a2  9a 01 0e 25 04 0b 00 01  |...........%....|
00000290  fc 91 01 21 b2 8a 01 44  48 f3 1e 8c 27 b0 1f 9a  |...!...DH...'...|
000002a0  26 80 02 33 33 33 33 33  33 33 33 33 33 33 33 33  |&..3333333333333|
000002b0  33 33 33 33 33 33 33 33  33 33 33 33 33 33 33 33  |3333333333333333|
*
00000320  33 33 33 32 23 23 32 33  22 32 32 33 33 32 23 33  |3332##23"22332#3|
00000330  23 23 23 33 33 33 33 33  32 23 23 22 33 33 33 33  |###333332##"3333|
00000340  33 33 33 33 33 33 33 32  23 33 33 33 33 33 32 33  |33333332#3333323|
00000350  33 33 33 33 33 33 33 33  23 33 33 33 33 33 23 33  |33333333#33333#3|
00000360  23 33 33 33 33 23 23 33  33 33 33 33 33 33 33 33  |#3333##333333333|
00000370  33 23 23 32 33 33 23 23  33 33 33 32 33 33 23 33  |3##233##333233#3|
00000380  22 33 33 33 33 33 23 33  33 32 23 33 22 33 23 33  |"33333#332#3"3#3|
…
```

**Comment by iceiix** [comment]
Getting closer, no longer crashes parsing chunk data, but it isn't quite correct either:

Screen Shot 2021-12-30 at 3 38 49 PM

Screen Shot 2021-12-30 at 3 41 50 PM

and server kicks for flying

**Comment by iceiix** [comment]
Screen Shot 2022-01-01 at 9 23 11 AM
Screen Shot 2022-01-01 at 9 21 01 AM

Note, 0x24 Particle_f64 IDs are wrong: `thread 'main' panicked at 'Err: Err("Failed to read all of packet 0x24, had 1 bytes left")', src/server/mod.rs:655:`, checked at least back to https://wiki.vg/index.php?title=Protocol&oldid=16918#Particle, possibly earlier - protocol/src/protocol/packet.rs has `field block_state: VarInt = when(|p: &Particle_f64| p.particle_id == 4 || p.particle_id == 25),` but 2 and 3 have a BlockState not 4 and 25, may need more particle packet variations. The problem manifests itself as crashing when e.g. falling, causing particle packets to be sent to the client. But this is separate from the chunk data packets.

**Comment by iceiix** [comment]
Screen Shot 2022-01-01 at 9 23 11 AM
Screen Shot 2022-01-01 at 9 21 01 AM

Note, 0x24 Particle_f64 IDs are wrong: `thread 'main' panicked at 'Err: Err("Failed to read all of packet 0x24, had 1 bytes left")', src/server/mod.rs:655:`, checked at least back to https://wiki.vg/index.php?title=Protocol&oldid=16918#Particle, possibly earlier - protocol/src/protocol/packet.rs has `field block_state: VarInt = when(|p: &Particle_f64| p.particle_id == 4 || p.particle_id == 25),` but 2 and 3 have a BlockState not 4 and 25, may need more particle packet variations. The problem manifests itself as crashing when e.g. falling, causing particle packets to be sent to the client. But this is separate from the chunk data packets.

At least some chunk data appears to be loading (though incorrect block IDs?):

Screen Shot 2022-01-01 at 9 47 30 AM

**Comment by ChillerDragon** [comment]
Love the detailed sharing of progress :slightly_smiling_face: :heart:

**Comment by iceiix** [comment]
1.18.2 ([758](https://wiki.vg/index.php?title=Protocol&oldid=17499))
1.19 (759) https://wiki.vg/Protocol
1.19.1 (760) 
are out now. 

Diffing 1.18.2 (758) vs 1.18.1/1.18 (757): https://wiki.vg/index.php?title=Protocol&type=revision&diff=17499&oldid=17341 - not many changes, only a few packets change to varints. Considering whether it would be worth updating to a newer version. There are many more changes from 1.8.1 (758) to 1.9 (759): https://wiki.vg/index.php?title=Protocol&type=revision&diff=17663&oldid=17499. Maybe updating directly to 1.19.x is too big of a change: focus on getting 1.18.x working first (either .1 or .2, not much of a difference).

**Comment by iceiix** [comment]
There is a significant change in how chunk sections are included. ≤1.17 uses a bit mask, and only sends non-empty sections. For a flat world only sending (0,0), this is one chunk section, beginning with:

```
bit_size = 4
count = 5
mapping i 0 = id 0
mapping i 1 = id 33
mapping i 2 = id 10
mapping i 3 = id 9
mapping i 4 = id 1
bi 0 = 1 = Bedrock at <0,0,0>
```

1.18+ removes the mask, and sends all 16 sections - but adds a new "single-valued palette" especially useful for sending air. Here's where our results differ. The changes on this branch so far read a single-valued palette, bit_size = 0, value = 0, as the first 4 sections, beginning with bi 0 = 0 = Air at <0,0,0>. There is a section with bedrock and bit_size = 4, but it is calculated to begin at 0,64,0. Logging in with vanilla and targeting the block confirms 0,0,0 is bedrock, 0,1,0 is dirt, up to 0,3,0, and then 0,4,0 is stone. But using [minecraft-chunk-dumper](https://github.com/PrismarineJS/minecraft-chunk-dumper), parsing the saved folder2/chunk_0_0.dump as 1.18.1, it _also_ recognizes the first 4 sections as single-valued 0 then the bedrock/dirt chunk, what can explain this? `ChunkColumn= require('prismarine-chunk')('1.18.1'); chunk=new ChunkColumn(); chunk.load(require('fs').readFileSync('folder2/chunk_0_0.dump')); chunk.sections`

**Comment by iceiix** [comment]
Skipping the chunk sections y<0, taking into account min_y, fixes the chunk offset:

Screen Shot 2022-07-31 at 5 04 54 PM

but is not the most elegant fix. A better fix would be to properly support min_y, factoring it into all block accesses, like [Botcraft](https://github.com/adepierre/Botcraft/commit/1f4d1599e9612697bce2cfcfcb598edfd7dd67b0) does. This would also avoid truncating negative y blocks.

**Comment by iceiix** [comment]
**Lighting**

1.17.1 with same chunk data has correct lighting, but 1.18.1 is missing lighting. Testing, it is not the sunlight - time set noon, time set night, adjusts the sun/moon lighting consistently. The block lights are missing. The lighting data _did_ move:

* 1.17.1: https://wiki.vg/index.php?title=Protocol&oldid=16918#Chunk_Data
* 1.18.1: https://wiki.vg/index.php?title=Protocol&oldid=17341#Chunk_Data_And_Update_Light

but in 1.17.1 (and earlier), we did not handle the `UpdateLight_` packets either. Pre-1.14 would read lighting from the chunk data packets:

```rust
                } else if self.protocol_version >= 451 {
                    // Skylight in update skylight packet for 1.14+
                } else {
                    data.read_exact(&mut section.block_light.data)?;
                    data.read_exact(&mut section.sky_light.data)?;
                }
```

and now it is in back - in 1.18.1+, but testing hardcoding writing 15 (max brightness) has no effect. "// Skylight in update skylight packet for 1.14+" is true, but again, `UpdateLight` packets are not handled yet (and have not significantly changed, compare: https://wiki.vg/index.php?title=Protocol&oldid=17341#Update_Light vs https://wiki.vg/index.php?title=Protocol&oldid=16918#Update_Light). Something else is missing.

But hardcoding Snapshot get_block_light and get_sky_light _does_ make the blocks more visible:

Screen Shot 2022-08-06 at 10 50 31 AM

except the player model is still dark:

Screen Shot 2022-08-06 at 10 50 33 AM

compare to 1.17.1:

Screen Shot 2022-08-06 at 10 57 16 AM

Adding logging, get_block_light is always 0 in 1.17.1 in this test. get_sky_light is 15 in 1.17.1 but all 0 in 1.18.1. Where is it set?

**Comment by iceiix** [comment]
Although this introduces some technical debt, it _does_ now allow connecting to 1.18.1 (757) - can be refined further in later protocol updates.

**Pull request merged**
