### PR TITLE
Migrate to glutin 0.24.0

### PR DESCRIPTION
**Pull request by mwkroening**
This upgrades glutin to 0.24.0 similar to #268. 

Related to #316.

What do you think?

### CODE REVIEW

**Comment by mwkroening** [comment]
I have appended a fix for #316.

**Comment by iceiix** [comment]
@mwkroening The changes look reasonable to me, thank you for putting this together, and Wayland support.

But I'm having some trouble with it, in my testing on macOS 10.15.4, after the first commit (https://github.com/iceiix/stevenarella/pull/317/commits/bc273dbe0ecf6c6b57533ffed026c68868628cff), rebased on `master`: on the title screen, no longer receiving correct mouse events. I can scroll through the servers (scrollWheel event), but mousing over the server list item no longer highlights the server and clicking has no effect. So I can't join any server :(

I suspect this could be related to hi-dpi cursor coordinates, as this iMac I'm testing on has a 2.0 scale factor. I recall seeing similar issues in my earlier attempt at porting to a newer glutin in #268. We may need to adjust the coordinates received in the mouse events by the scale factor...

**Comment by iceiix** [comment]
#268 updated to glutin 0.22.0, will use this PR + #323 to look into updating to glutin 0.24.0

**Comment by iceiix** [comment]
Merged your fix for #316 https://github.com/iceiix/stevenarella/commit/54763da22ddb86bf7b7f570b084f9413ea1f9b7e, seems fine (thanks!).

However, I'm having trouble with the changes to update to glutin 0.24, at least on my system it introduces a bug, not present with glutin 0.22. I believe this is the only part of this PR I haven't merged in yet. Split it out to test separately in https://github.com/iceiix/stevenarella/pull/334, lets continue there

**Pull request closed without merging**
