### PR TITLE
Update to glutin 0.26.0 + winit 0.24.0

### PR DESCRIPTION
**Pull request by iceiix**
Combining parts of #317 and #323

### CODE REVIEW

**Comment by iceiix** [comment]
This compiles and runs, but introduces a serious problem on my system (macOS, iMac, 2.0 hidpi): cursor tracking is broken, for example, in this screenshot my cursor is on the tip of the "v" in the logo but it highlights the first server list entry:

Screen Shot 2020-06-20 at 2 31 52 PM

If I move the mouse down so it is actually over the first server list entry, then it highlights the last server list entry box shown:

Screen Shot 2020-06-20 at 2 31 54 PM

If I revert this commit, going back to the master branch with glutin 0.22.0 + winit 0.20.0, then the problem no longer occurs (mouse tracking is accurate).

Not clear how the glutin/winit update changed this behavior. The only code change here besides the dependency update is updating for the new ModifiersChange event, which seems unrelated. It also doesn't seem to be related to hidpi because the scaling doesn't appear to be off by 2.0 or 0.5, though it might be.

**Comment by iceiix** [comment]
Actually, this could be hidpi-related. Looks like the mouse coordinates are 2x off.

**Comment by iceiix** [comment]
Reverting `.to_logical::<f64>(game.dpi_factor).into();` to `.into();` seems to get closer, but isn't quite right. In this screenshot, the mouse is slightly over halfway down the first server list item (2/3?), but the second server list item is highlighted:

Screen Shot 2020-06-20 at 2 52 16 PM

it also doesn't seem like the right solution. Why does winit change how they handle the dpi scale factor so frequently? Needs more investigation to see what they changed and how to update for winit 0.20 to winit 0.22.

This appears relevant: https://github.com/rust-windowing/winit/blob/master/CHANGELOG.md#0220-2020-03-09

> 0.22.0 (2020-03-09)
> Breaking: Use i32 instead of u32 for position type in WindowEvent::Moved.
>
> 0.21.0 (2020-02-04)
> Breaking: WindowEvent::CursorMoved changed to f64 units, preserving high-precision data supplied by most backends

**Comment by mwkroening** [comment]
I can confirm that this breaks cursor tracking on x11. I'm not sure, if I'll find time to dig deeper soon though.

**Comment by iceiix** [comment]
Rebased on top of master with rustfmt changes

**Comment by iceiix** [comment]
Another mouse tracking issue I noticed, while investigating #36 - on Windows on VMware Fusion, even on the master branch (without the changes in this PR), the mouse position is slightly off (about 1/3 of the server list, similar symptoms as described here). This may be related to the virtualization environment, to glutin/winit, or to the DPI scale factor..

**Comment by iceiix** [comment]
Updated to glutin 0.25.1 + winit 0.23.0, to close dependabot #410 #407 (and removed Cargo.lock from this branch to ease merging), the problem persists. Looks like we'll have to figure out why this broke...

**Comment by iceiix** [comment]
Updated again, to glutin 0.26.0 and winit 0.24.0 to close #430 and #431

**Comment by iceiix** [comment]
Note: updating only to glutin 0.23.0 reproduces the mouse tracking bug, according to #418 this transitively updates winit

**Comment by iceiix** [comment]
```diff
--- a/src/main.rs
+++ b/src/main.rs
@@ -357,7 +357,7 @@ fn main2() {
         let delta = (diff.subsec_nanos() as f64) / frame_time;
         let physical_size = window.window().inner_size();
         let (physical_width, physical_height) = physical_size.into();
-        let (width, height) = physical_size.to_logical::<f64>(game.dpi_factor).into();
+        let (width, height) = window.window().inner_size().into();
 
         let version = {
             let try_res = game.resource_manager.try_write();
```

fixes the mouse scaling, but shrinks the UI:

Screen Shot 2020-12-19 at 6 58 27 PM

**Comment by iceiix** [comment]
Have a fix, it works at least on my system (hopefully doesn't break others... but this code now appears "correct", it was only working before due to a library bug)

**Pull request merged**
